version: "3"

services:
  docker-mariaDB:
    container_name: docker-pointDB
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: planit_point
      MYSQL_USER: planit
      MYSQL_PASSWORD: planit1234
    ports:
      - 8002:3306

  docker-spring:
    container_name: docker-point
    image: dlaudghtn/point-service:t1
    restart: on-failure
    depends_on:
      - docker-mariaDB
    ports:
      - 9004:9004
